spring:
    application:
        name: tes.co.id
server:
    port: 8989
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8090/eureka/
---
spring:
    profiles: dev
    application:
        name: tes.co.id
server:
    port: 8989
eureka:
    client:
        serviceUrl:
            defaultZone: http://192.168.9.49:8761/eureka/

---
spring:
    profiles: prod
    application:
        name: egp.co.id
eureka:
    instance:
        hostname: https://egp-app.herokuapp.com
    client:
        serviceUrl:
            defaultZone: https://eureka-cloud.herokuapp.com/eureka/
            
        
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000    
